@rpcURL=https://api.mycryptoapi.com/eth
# @rpcURL=https://eth-mainnet.public.blastapi.io
# @rpcURL=http://222.106.187.14:50001

# @rpcURL=http://lcd-evmos.cosmostation.io:8545/

###
GET https://lcd-axelar-testnet.cosmostation.io/cosmos/staking/v1beta1/delegators/tgrade1ursv4z57pw8ly2jsgn09dyjha4qrk7aec90q3a/unbonding_delegations
Cosmostation: extension

### 
POST https://eth-mainnet.public.blastapi.io
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [
        20, "pending", [10, 30, 50]
    ],
    "id": 0
}

### 
POST https://eth-sepolia.g.alchemy.com/v2/y8g-2-14cWbAO_xGFIBMa0y32jxKYAj8
content-type: application/json

{"jsonrpc":"2.0","id":124,"method":"eth_getLogs","params":[{"address":["0xcca9d5f0a3c58b6f02bd0985fc7f9420ea24c1f0"],"fromBlock":"0x3fc707","toBlock":"finalized","topics":[["0x498a04382650bc110983392ed12ab27595af8ece270a344fc70d773d2481043a"],["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000"]]}]}

### 
POST http://222.106.187.14:50001
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [
        20, "pending", [10, 30, 50]
    ],
    "id": 0
}

### 
POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [
        20, "pending", [10, 30, 50]
    ],
    "id": 0
}


### eth_estimateGas

POST {{rpcURL}} 
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [{
        "from": "0xe4a7e953486d01d4fdc76986a0c88fa4f87b30e5",
        "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
        "data": "0xa9059cbb000000000000000000000000e4a7e953486d01d4fdc76986a0c88fa4f87b30e5000000000000000000000000000000000000000000000000000009184e72a000"
    }],
    "id": 1
}

### eth_estimateGas

POST {{rpcURL}} 
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [{
        "from": "0xE4A7e953486D01d4Fdc76986a0c88fa4F87B30e5",
        "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
        "data": "0xa9059cbb000000000000000000000000dddf66022c8307222dc8a118f4de97e131c1793600000000000000000000000000000000000000000000000000005af3107a4000"
    }],
    "id": 1
}

### eth_accounts

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_accounts",
    "params": [],
    "id": 1
}

### eth_getBalance
POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": ["0xE4A7e953486D01d4Fdc76986a0c88fa4F87B30e5", "latest"],
    "id": 1
}

### web3_clientVersion
POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "web3_clientVersion",
    "params": [],
    "id": 1
}

### eth_mining

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_mining",
    "params": [],
    "id": 1
}

### eth_blockNumber

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 1
}

### eth_chainId

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_chainId",
    "params": [],
    "id": 1
}

### eth_getBlockByHash

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByHash",
    "params": ["0xb47e05ab333e436bec1f062d480e604d2323b12afe5212bf6e2b78fdd2c4e7d2", true],
    "id": 1
}

### eth_getBlockTransactionCountByHash

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getBlockTransactionCountByHash",
    "params": ["0xb47e05ab333e436bec1f062d480e604d2323b12afe5212bf6e2b78fdd2c4e7d2"],
    "id": 1
}

### eth_getBlockTransactionCountByHash

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_sendTransaction",
    "params": [],
    "id": 1
}

### eth_getTransactionCount (get nonce)

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionCount",
    "params": [
        "0xE4A7e953486D01d4Fdc76986a0c88fa4F87B30e5", "latest"
    ],
    "id": 0
}

### 0xb47e05ab333e436bec1f062d480e604d2323b12afe5212bf6e2b78fdd2c4e7d2

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": [
        "0xb47e05ab333e436bec1f062d480e604d2323b12afe5212bf6e2b78fdd2c4e7d2"
    ],
    "id": 0
}

### eth_getTransactionByHash (get nonce)

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {"data": "0x70a08231000000000000000000000000e4a7e953486d01d4fdc76986a0c88fa4f87b30e5", "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"},
        "latest"
    ],
    "id": 0
}

### eth_getCode

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0x7f268357A8c2552623316e2562D90e642bB538E5",
        "latest"
    ],
    "id": 0
}

### "0x02f86901050a82012c82520894dddf66022c8307222dc8a118f4de97e131c179368502540be40080c080a0cf3e6e4df3c5d2d33d3a39fecfb632e829ca7fd3c9a11777314f5680ad8a2a29a02b6fb83f2ea230b0283d3d3bcc9412a264d1fd4f3444d34099dd4e14e5601574"

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_sendRawTransaction",
    "params": [
 "0xf86b0b85069bb7c9ce82520894dddf66022c8307222dc8a118f4de97e131c1793687038d7ea4c680008025a0ea657665756d2cbd78f4e01fc35d3624e564c8d04d4e0142828d31ede3b9aa81a06079e5325d8a941f495f7eb985dcd202c4ff805eb31f99a3036ea23280361079"
    ],
    "id": 0
}


###

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 0
}

###

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["pending", false],
    "id": 0
}

### eth_gasPrice

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_gasPrice",
    "params": [],
    "id": 1
}

### eth_getTransactionReceipt

POST {{rpcURL}}
content-type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionReceipt",
    "params": ["0x43c88fc54a7e2fcc25c6e813a0d532cb0688072db052e065199ce103436e7e77"],
    "id": 1
}
