import type { CosmosChain, EthereumChain, EthereumNetwork } from '~/types/chain';

export const LINE_TYPE = {
  COSMOS: 'COSMOS',
  ETHEREUM: 'ETHEREUM',
} as const;

export const COSMOS_CHAINS: CosmosChain[] = [
  {
    id: '62a8e13a-3107-40ef-ade4-58de45aa6c1f',
    line: LINE_TYPE.COSMOS,
    chainId: 'cosmoshub-4',
    chainName: 'cosmos',
    restURL: 'https://lcd-cosmos.cosmostation.io',
    baseDenom: 'uatom',
    displayDenom: 'atom',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'cosmos' },
  },
  {
    id: 'd86e2b4e-e422-4b58-b687-f1de03cde152',
    line: LINE_TYPE.COSMOS,
    chainId: 'irishub-1',
    chainName: 'iris',
    restURL: 'https://lcd-iris.cosmostation.io',
    baseDenom: 'uiris',
    displayDenom: 'iris',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'iaa' },
  },
  {
    id: '634e5e88-0a26-4ef5-92b5-dbf4cf040a8a',
    line: LINE_TYPE.COSMOS,
    chainId: 'kava-8',
    chainName: 'kava',
    restURL: 'https://lcd-kava.cosmostation.io',
    baseDenom: 'ukava',
    displayDenom: 'kava',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'kava' },
  },
  {
    id: 'c3e5474b-8cf7-467e-b6a8-706d2b694e5a',
    line: LINE_TYPE.COSMOS,
    chainId: 'laozi-mainnet',
    chainName: 'band',
    restURL: 'https://lcd-band.cosmostation.io',
    baseDenom: 'uband',
    displayDenom: 'band',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "494'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'band' },
  },
  {
    id: 'b869bcf8-f489-443a-9be4-56cac21f6f53',
    line: LINE_TYPE.COSMOS,
    chainId: 'akashnet-2',
    chainName: 'akash',
    restURL: 'https://lcd-akash.cosmostation.io',
    baseDenom: 'uakt',
    displayDenom: 'akt',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'akash' },
  },
  {
    id: '29d61a8d-6bbe-4524-afa5-6f70931bcdee',
    line: LINE_TYPE.COSMOS,
    chainId: 'shentu-2.2',
    chainName: 'certik',
    restURL: 'https://lcd-certik.cosmostation.io',
    baseDenom: 'uctk',
    displayDenom: 'ctk',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'certik' },
  },
  {
    id: '8c72318f-8279-4d37-a457-1cd4c0b1f160',
    line: LINE_TYPE.COSMOS,
    chainId: 'sentinelhub-2',
    chainName: 'sentinel',
    restURL: 'https://lcd-sentinel.cosmostation.io',
    baseDenom: 'udvpn',
    displayDenom: 'DVPN',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'sent' },
  },
  {
    id: '58c55107-2df3-4851-a68e-fee203308be2',
    line: LINE_TYPE.COSMOS,
    chainId: 'core-1',
    chainName: 'persistence',
    restURL: 'https://lcd-persistence.cosmostation.io',
    baseDenom: 'uxprt',
    displayDenom: 'xprt',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'persistence' },
  },
  {
    id: '3b8e015e-ab6c-4095-9dd8-57e62f437f4f',
    line: LINE_TYPE.COSMOS,
    chainId: 'fetchhub-2',
    chainName: 'fetch.ai',
    restURL: 'https://lcd-fetchai.cosmostation.io',
    baseDenom: 'afet',
    displayDenom: 'fet',
    decimal: 18,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'fetch' },
  },
  {
    id: 'ba43a35a-0861-486a-9ce9-c23fb1ba610c',
    line: LINE_TYPE.COSMOS,
    chainId: 'sifchain-1',
    chainName: 'sifchain',
    restURL: 'https://lcd-sifchain.cosmostation.io',
    baseDenom: 'rowan',
    displayDenom: 'rowan',
    decimal: 18,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'sif' },
  },
  {
    id: 'b006dccc-ff1e-4c5a-95ad-94f313029d93',
    line: LINE_TYPE.COSMOS,
    chainId: 'crypto-org-chain-mainnet-1',
    chainName: 'crypto.org',
    restURL: 'https://lcd-cryptocom.cosmostation.io',
    baseDenom: 'basecro',
    displayDenom: 'cro',
    decimal: 8,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'cro' },
  },
  {
    id: 'f850280f-316c-44ab-9624-c8d760dbca8c',
    line: LINE_TYPE.COSMOS,
    chainId: 'kichain-2',
    chainName: 'kichain',
    restURL: 'https://lcd-kichain.cosmostation.io',
    baseDenom: 'uxki',
    displayDenom: 'xki',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'ki' },
  },
  {
    id: '320cfa03-401d-44b5-a40a-0de7c0d705eb',
    line: LINE_TYPE.COSMOS,
    chainId: 'iov-mainnet-ibc',
    chainName: 'starname',
    restURL: 'https://lcd-iov.cosmostation.io',
    baseDenom: 'uiov',
    displayDenom: 'iov',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "234'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'star' },
  },
  {
    id: '1272070c-b1f0-455e-9bb7-ff434b5011e9',
    line: LINE_TYPE.COSMOS,
    chainId: 'panacea-3',
    chainName: 'medibloc',
    restURL: 'https://lcd-medibloc.cosmostation.io',
    baseDenom: 'umed',
    displayDenom: 'med',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'panacea' },
  },
  {
    id: 'b6b1f158-9d6c-4779-a40d-9be657555612',
    line: LINE_TYPE.COSMOS,
    chainId: 'emoney-3',
    chainName: 'emoney',
    restURL: 'https://lcd-emoney.cosmostation.io',
    baseDenom: 'ungm',
    displayDenom: 'ngm',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'emoney' },
  },
  {
    id: '2be3f1c4-8c2e-4fc9-80c8-5877b0bb77c8',
    line: LINE_TYPE.COSMOS,
    chainId: 'titan-1',
    chainName: 'rizon',
    restURL: 'https://lcd-rizon.cosmostation.io',
    baseDenom: 'uatolo',
    displayDenom: 'atolo',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'rizon' },
  },
  {
    id: '23076a4e-8bba-4e36-8563-2c30948f290c',
    line: LINE_TYPE.COSMOS,
    chainId: 'juno-1',
    chainName: 'juno',
    restURL: 'https://lcd-juno.cosmostation.io',
    baseDenom: 'ujuno',
    displayDenom: 'juno',
    decimal: 6,
    bip44: {
      purpose: "44'",
      coinType: "118'",
      account: "0'",
      change: '0',
    },
    bech32Prefix: { address: 'juno' },
  },
];

export const ETHEREUM_NETWORKS: EthereumNetwork[] = [
  {
    id: '63c2c3dd-7ab1-47d7-9ec8-c70c64729cc6',
    chainId: '1',
    networkName: 'mainnet',
    rpcURL: 'http://61.74.179.193:50001',
    baseDenom: 'weth',
    displayDenom: 'eth',
    decimal: 16,
    explorerURL: 'https://etherscan.io',
  },
];

export const ETHEREUM_CHAINS: EthereumChain[] = [
  {
    id: '33c328b1-2d5f-43f1-ac88-25be1a5abf6c',
    chainName: 'ethereum',
    line: LINE_TYPE.ETHEREUM,
    networks: ETHEREUM_NETWORKS,
    bip44: {
      purpose: "44'",
      coinType: "60'",
      account: "0'",
      change: '0',
    },
  },
];

export const CHAINS = [...COSMOS_CHAINS, ...ETHEREUM_CHAINS];
