import { CURRENCY_TYPE } from './extensionStorage';

export const CURRENCY_SYMBOL = {
  [CURRENCY_TYPE.USD]: '$',
  [CURRENCY_TYPE.KRW]: '₩',
  [CURRENCY_TYPE.EUR]: '€',
  [CURRENCY_TYPE.JPY]: '¥',
  [CURRENCY_TYPE.CNY]: '¥',
  [CURRENCY_TYPE.BTC]: 'BTC',
  [CURRENCY_TYPE.ETH]: 'ETH',
} as const;

export const CURRENCY_DECIMALS = {
  [CURRENCY_TYPE.USD]: 3,
  [CURRENCY_TYPE.KRW]: 0,
  [CURRENCY_TYPE.EUR]: 3,
  [CURRENCY_TYPE.JPY]: 1,
  [CURRENCY_TYPE.CNY]: 3,
  [CURRENCY_TYPE.BTC]: 8,
  [CURRENCY_TYPE.ETH]: 7,
} as const;
