export const PATH = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  WALLET: '/wallet',
  SETTING__CHANGE_PASSWORD: '/setting/change-password',
  SETTING__CHANGE_LANGUAGE: '/setting/change-language',
  SETTING__CHANGE_CURRENCY: '/setting/change-currency',
  CHAIN__MANAGEMENT: '/chain/management',
  CHAIN__MANAGEMENT__USE: '/chain/management/use',
  ACCOUNT__MANAGEMENT: '/account/management',
  ACCOUNT__CREATE: '/account/create',
  RESTORE: '/restore',
  REGISTER: '/register',
  REGISTER__PASSWORD: '/register/password',
  REGISTER__ACCOUNT: '/register/account',
  REGISTER__ACCOUNT__MNEMONIC: '/register/account/mnemonic',
  REGISTER__ACCOUNT__PRIVATE_KEY: '/register/account/private-key',
  REGISTER__ACCOUNT__NEW: '/register/account/new',
} as const;
