export const SUI_POPUP_METHOD_TYPE = {
  SUI__CONNECT: 'sui_connect',
  SUI__SIGN_TRANSACTION_BLOCK: 'sui_signTransactionBlock',
  SUI__SIGN_TRANSACTION: 'sui_signTransaction',
  SUI__SIGN_AND_EXECUTE_TRANSACTION_BLOCK: 'sui_signAndExecuteTransactionBlock',
  SUI__SIGN_AND_EXECUTE_TRANSACTION: 'sui_signAndExecuteTransaction',
  SUI__SIGN_MESSAGE: 'sui_signMessage',
  SUI__SIGN_PERSONAL_MESSAGE: 'sui_signPersonalMessage',
  SUI__GET_ACCOUNT: 'sui_getAccount',
} as const;

export const SUI_NO_POPUP_METHOD_TYPE = {
  SUI__BATCH_TRANSACTION: 'sui_batchTransaction',
  SUI__DRY_RUN_TRANSACTION: 'sui_dryRunTransaction',
  SUI__EXECUTE_TRANSACTION: 'sui_executeTransaction',
  SUI__EXECUTE_TRANSACTION_SERIALIZED_SIG: 'sui_executeTransactionSerializedSig',
  SUI__GET_BALANCE: 'sui_getBalance',
  SUI__GET_COIN_METADATA: 'sui_getCoinMetadata',
  SUI__GET_COINS: 'sui_getCoins',
  SUI__GET_COMMITTEEI_NFO: 'sui_getCommitteeInfo',
  SUI__GET_EVENTS: 'sui_getEvents',
  SUI__GET_MOVE_FUNCTION_ARG_TYPES: 'sui_getMoveFunctionArgTypes',
  SUI__GET_NORMALIZED_MOVE_FUNCTION: 'sui_getNormalizedMoveFunction',
  SUI__GET_NORMALIZED_MOVE_MODULE: 'sui_getNormalizedMoveModule',
  SUI__GET_NORMALIZED_MOVE_MODULES_BY_PACKAGE: 'sui_getNormalizedMoveModulesByPackage',
  SUI__GET_NORMALIZED_MOVE_STRUCT: 'sui_getNormalizedMoveStruct',
  SUI__GET_OBJECT: 'sui_getObject',
  SUI__GET_OBJECTS_OWNED_BY_ADDRESS: 'sui_getObjectsOwnedByAddress',
  SUI__GET_OBJECTS_OWNED_BY_OBJECT: 'sui_getObjectsOwnedByObject',
  SUI__GET_RAW_OBJECT: 'sui_getRawObject',
  SUI__GET_SUI_SYSTEM_STATE: 'sui_getSuiSystemState',
  SUI__GET_TOTAL_SUPPLY: 'sui_getTotalSupply',
  SUI__GET_TOTAL_TRANSACTION_NUMBER: 'sui_getTotalTransactionNumber',
  SUI__GET_TRANSACTION: 'sui_getTransaction',
  SUI__GET_TRANSACTION_AUTH_SIGNERS: 'sui_getTransactionAuthSigners',
  SUI__GET_TRANSACTIONS: 'sui_getTransactions',
  SUI__GET_TRANSACTIONS_IN_RANGE: 'sui_getTransactionsInRange',
  SUI__MERGE_COINS: 'sui_mergeCoins',
  SUI__MOVE_CALL: 'sui_moveCall',
  SUI__PAY: 'sui_pay',
  SUI__PAY_ALL_SUI: 'sui_payAllSui',
  SUI__PAY_SUI: 'sui_paySui',
  SUI__PUBLISH: 'sui_publish',
  SUI__SPLIT_COIN: 'sui_splitCoin',
  SUI__SPLIT_COIN_EQUAL: 'sui_splitCoinEqual',
  SUI__SUBSCRIBE_EVENT: 'sui_subscribeEvent',
  SUI__TRANSFER_OBJECT: 'sui_transferObject',
  SUI__TRANSFER_SUI: 'sui_transferSui',
  SUI__TRY_GET_PAST_OBJECT: 'sui_tryGetPastObject',

  // custom
  SUI__GET_PERMISSIONS: 'sui_getPermissions',
  SUI__DISCONNECT: 'sui_disconnect',
  SUI__GET_CHAIN: 'sui_getChain',
} as const;

export const SUI_METHOD_TYPE = {
  ...SUI_NO_POPUP_METHOD_TYPE,
  ...SUI_POPUP_METHOD_TYPE,
} as const;
